### ISSUE TITLE
Error starting virtual camera

### ISSUE THREAD

**Issue by michael135** [prabhakar-sivanesan/MS-Teams-background-changer#1]
When running:

`sudo modprobe v4l2loopback video_nr=20 card_name="Virtual Camera 1" exclusive_caps=1`

I'm getting:
`modprobe: ERROR: could not insert 'v4l2loopback': Operation not permitted`

**Comment by prabhakar-sivanesan** [comment]
Hi Micheal,

Please give some additional information to debug the problem like,
1. OS type
2. Commands used
3. Also, information about previous version of v4l2loopback module installed, if any.

**Comment by michael135** [comment]
Hi Prabhakar,

1. Ubuntu 20.04
2. Commans as in Readme.
3. Regarding the v4l2loopback version:
```
apt -a list v4l2loopback-dkms
Listing... Done
v4l2loopback-dkms/focal-updates,focal-updates,focal-security,focal-security,now 0.12.3-1ubuntu0.4 all [installed]
v4l2loopback-dkms/focal,focal 0.12.3-1 all
```

**Comment by prabhakar-sivanesan** [comment]
I personally didn't face this issues, but it looks like building the [v4l2loopback](https://github.com/umlaeute/v4l2loopback) module from source will solve this issue as suggested here [here](https://askubuntu.com/a/1264352). 
Step 1: Remove existing v4l2 module using `sudo apt-get remove v4l2loopback-dkms`
Step 2: Clone [v4l2loopback](https://github.com/umlaeute/v4l2loopback) module and build from source `make && sudo make install` and then run `sudo depmod -a`
Step 3: Create virtual camera using `sudo modprobe v4l2loopback video_nr=20 card_name="Virtual Camera 1"`

Please try these steps and let me know the whether the issue is solved.

P.S: I have also updated the readme with code to create virtual camera. Please refer that or clone the latest repo.

Edit 1 (23/07/2022): I encountered the same issue on couple of my friends machine. The above mentioned steps solved in one machine and not for the other. So I had to disable the `Secure Boot` option in the BIOS settings and it solved the issue finally on the other machine.
